const lorem_data = [
  'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec et consequat tortor. Suspendisse potenti. Suspendisse potenti. Donec pellentesque turpis vel massa scelerisque, id hendrerit nisi semper. Quisque turpis ipsum, blandit id enim et, iaculis porttitor turpis. Phasellus at sem sollicitudin urna blandit dignissim at cursus quam. Nam mattis auctor nulla, pellentesque vestibulum eros tristique non. Aenean sit amet diam urna. Donec odio eros, mollis a elit fermentum, tincidunt sodales nisl. Praesent at nisi sagittis, pellentesque sem eget, finibus velit. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Suspendisse potenti. Donec vehicula enim purus, lacinia luctus libero ultricies nec. Suspendisse tincidunt ultricies risus, id consectetur ipsum ornare at. Sed luctus felis a luctus ultrices. Vestibulum rhoncus nunc in varius tincidunt.',
  'Nulla consequat enim ipsum, sit amet gravida lacus scelerisque nec. Vestibulum fringilla lorem in metus luctus tristique. Proin iaculis urna porttitor dolor egestas accumsan. Curabitur a odio gravida, laoreet mi at, rutrum libero. Cras consequat ex lobortis dolor ullamcorper, eu posuere arcu interdum. Aliquam ultrices tortor non diam semper tristique. Donec pretium ultrices enim aliquet lacinia. Nunc molestie rutrum urna, vitae tincidunt orci venenatis vel. Nullam nisi nunc, aliquam sed nisi vel, lacinia suscipit magna. Etiam venenatis dolor et rutrum egestas. Morbi ac ullamcorper arcu.',
  'Quisque et fermentum turpis. Curabitur aliquet gravida consequat. Ut mattis arcu neque, quis consequat ligula venenatis eget. Aliquam pharetra augue et commodo pharetra. Vestibulum semper dapibus tellus, id hendrerit nisl rutrum sed. Sed ornare elit sit amet fringilla facilisis. Quisque at velit aliquet, facilisis elit accumsan, cursus elit. Vivamus dictum nisi ac mi imperdiet, et semper arcu auctor.',
  'Donec lobortis vestibulum eros ut fermentum. Integer dolor leo, vestibulum vel placerat ac, accumsan ut dolor. Nunc tortor ante, lacinia id erat sed, facilisis rutrum dui. Sed luctus lectus magna, aliquet pharetra turpis laoreet non. Morbi erat magna, sagittis a tristique a, rhoncus et justo. Nullam eget sem ut risus vestibulum suscipit. Quisque et iaculis lorem.',
  'Aliquam erat volutpat. Etiam at dolor ut orci commodo suscipit consectetur in dui. Cras a justo non lectus fringilla pharetra. Vivamus sagittis sapien est, sed imperdiet urna pulvinar vel. Pellentesque in turpis feugiat, pulvinar nunc sed, efficitur ex. Fusce eget quam ipsum. Donec congue lacinia dolor. Sed vitae libero at ipsum laoreet mattis nec sed velit. Quisque accumsan diam ac urna placerat, et molestie ex sollicitudin. Fusce est turpis, gravida et enim ac, ullamcorper fermentum elit. Nunc pharetra ut purus vehicula dignissim. Pellentesque venenatis, nisl eget tristique elementum, purus magna blandit elit, non venenatis elit risus vitae magna. Vestibulum fermentum massa velit, quis rutrum sem interdum vel. Mauris eget blandit lorem.',
];

export default lorem_data;
